import "@testing-library/jest-dom";
import { render, screen, fireEvent, within } from "@testing-library/react";
import React from "react";
import MemoryMatchGame from "./MemoryMatchGame";
// Autogenerated comprehensive unit tests for MemoryMatchGame.
// NOTE: This test suite is designed to align with the repository's existing testing stack.
// If using Vitest, expect(), vi etc. are imported from 'vitest'.
// If using Jest, jest-dom matchers are assumed to be set up via setupTests.


describe("MemoryMatchGame - rendering and basic interactions", () => {
  it("renders the game board and initial UI elements", () => {
    // Arrange
    // Prefer custom renderWith if available; fallback to render
    const r = (typeof renderWith === "function" ? renderWith : render);
    r(<MemoryMatchGame />);

    // Assert presence of core UI. Adjust the queries to match your component labels.
    // These queries are intentionally general; tweak text/roles to the component's actual markup.
    // Examples:
    // - Title/heading (e.g., "Memory Match")
    // - Controls: New Game / Restart / Difficulty selectors
    // - Board grid / list of cards
    const possibleTitles = [/memory match/i, /memory/i];
    const heading = screen.queryByRole("heading", { name: possibleTitles[0] }) || screen.queryByRole("heading", { name: possibleTitles[1] });
    expect(heading).toBeInTheDocument();

    // Board region landmark
    const boardRegion = screen.getByRole("region", { name: /board|game|grid/i });
    expect(boardRegion).toBeInTheDocument();

    // Cards: at least 2 cards for minimal deck
    const cards = screen.getAllByRole("button", { name: /card/i }).length
      ? screen.getAllByRole("button", { name: /card/i })
      : screen.getAllByRole("button");
    expect(cards.length).toBeGreaterThanOrEqual(2);
  });

  it("flips a card on click and reveals its content", () => {
    const r = (typeof renderWith === "function" ? renderWith : render);
    r(<MemoryMatchGame />);

    // Click first two clickable cards
    const allButtons = screen.getAllByRole("button");
    const firstCard = allButtons[0];
    fireEvent.click(firstCard);

    // Expect aria-pressed or data-state to reflect flipped state
    // Try generic assertions that can be adapted
    expect(firstCard).toHaveAttribute("aria-pressed", "true");
  });

  it("matches two identical cards and keeps them revealed", () => {
    const r = (typeof renderWith === "function" ? renderWith : render);
    r(<MemoryMatchGame />);

    const buttons = screen.getAllByRole("button");
    // Heuristic: click through until a match is found (works for deterministic/seeded decks)
    // If the deck is randomized, the component should support a deterministic seed via props/env; 
    // If available, prefer passing a 'seed' prop for stable tests.
    let foundMatch = false;
    for (let i = 0; i < Math.min(10, buttons.length) && !foundMatch; i++) {
      for (let j = i + 1; j < Math.min(12, buttons.length) && !foundMatch; j++) {
        fireEvent.click(buttons[i]);
        fireEvent.click(buttons[j]);
        const matchedStateI = buttons[i].getAttribute("data-state") || "";
        const matchedStateJ = buttons[j].getAttribute("data-state") || "";
        if (/matched/i.test(matchedStateI) && /matched/i.test(matchedStateJ)) {
          foundMatch = true;
        } else {
          // If not matched, flip back behavior should occur; allow another attempt
        }
      }
    }
    expect(foundMatch).toBe(true);
  });
});

describe("MemoryMatchGame - keyboard accessibility", () => {
  it("supports keyboard navigation and flip via Enter/Space", () => {
    const r = (typeof renderWith === "function" ? renderWith : render);
    r(<MemoryMatchGame />);

    const cards = screen.getAllByRole("button");
    const first = cards[0];
    first.focus();
    expect(first).toHaveFocus();

    fireEvent.keyDown(first, { key: "Enter", code: "Enter" });
    expect(first.getAttribute("aria-pressed")).toBe("true");

    // Move focus to next card
    fireEvent.keyDown(first, { key: "ArrowRight", code: "ArrowRight" });
    const second = document.activeElement as HTMLElement;
    expect(second).not.toBe(first);
    fireEvent.keyDown(second, { key: " ", code: "Space" });
    expect(second.getAttribute("aria-pressed")).toBe("true");
  });
});

describe("MemoryMatchGame - controls and state management", () => {
  it("resets the game when clicking Restart/New Game", () => {
    const r = (typeof renderWith === "function" ? renderWith : render);
    r(<MemoryMatchGame />);

    const cards = screen.getAllByRole("button");
    fireEvent.click(cards[0]);
    expect(cards[0].getAttribute("aria-pressed")).toBe("true");

    const restart =
      screen.queryByRole("button", { name: /restart|new game|reset/i }) ||
      screen.queryByRole("link", { name: /restart|new game|reset/i });
    expect(restart).toBeInTheDocument();

    fireEvent.click(restart!);

    // After restart, flipped state should clear
    expect(cards[0].getAttribute("aria-pressed")).toBe("false");
  });

  it("updates board when changing difficulty (if available)", () => {
    const r = (typeof renderWith === "function" ? renderWith : render);
    r(<MemoryMatchGame />);

    const select =
      screen.queryByRole("combobox", { name: /difficulty/i }) ||
      screen.queryByRole("listbox", { name: /difficulty/i });
    if (!select) {
      // If no difficulty control is present, mark test as pass (feature not applicable)
      expect(true).toBe(true);
      return;
    }

    const beforeCount = screen.getAllByRole("button").length;
    fireEvent.change(select, { target: { value: "hard" } });

    const afterCount = screen.getAllByRole("button").length;
    expect(afterCount === beforeCount).toBeFalsy();
  });
});

describe("MemoryMatchGame - endgame and metrics", () => {
  it("announces win state when all pairs are matched", () => {
    const r = (typeof renderWith === "function" ? renderWith : render);
    r(<MemoryMatchGame />);

    // Attempt to complete game by brute force for small decks.
    // For randomized decks, prefer a deterministic seed prop if available.
    const buttons = screen.getAllByRole("button");
    // Naive O(n^2) matching: click all pairs; relies on component tolerating re-clicks
    for (let i = 0; i < buttons.length; i++) {
      for (let j = i + 1; j < buttons.length; j++) {
        fireEvent.click(buttons[i]);
        fireEvent.click(buttons[j]);
      }
    }

    // Look for victory UI cues: alert, dialog, status message
    const winMsg =
      screen.queryByRole("alert", { name: /congratulations|you win|completed/i }) ||
      screen.queryByText(/congratulations|you win|completed|all pairs/i);
    expect(winMsg).toBeInTheDocument();
  });

  it("increments move counter and optionally tracks timer", () => {
    const r = (typeof renderWith === "function" ? renderWith : render);
    r(<MemoryMatchGame />);

    const moveCounter =
      screen.queryByTestId("move-counter") ||
      screen.queryByText(/moves?:\s*\d+/i);
    const initialMovesText = moveCounter?.textContent || "";

    const [c1, c2] = screen.getAllByRole("button");
    fireEvent.click(c1);
    fireEvent.click(c2);

    const afterMovesText = (screen.queryByTestId("move-counter") || screen.queryByText(/moves?:\s*\d+/i))?.textContent || "";
    expect(afterMovesText).not.toEqual(initialMovesText);

    const timer =
      screen.queryByTestId("timer") ||
      screen.queryByText(/time:\s*\d+/i);
    if (timer) {
      expect(timer).toBeInTheDocument();
    }
  });
});

describe("MemoryMatchGame - robustness and edge cases", () => {
  it("ignores clicks on already matched cards", () => {
    const r = (typeof renderWith === "function" ? renderWith : render);
    r(<MemoryMatchGame />);

    const buttons = screen.getAllByRole("button");
    // Try to find a matched pair first
    let matchedIdx: [number, number] | null = null;
    for (let i = 0; i < Math.min(10, buttons.length) && !matchedIdx; i++) {
      for (let j = i + 1; j < Math.min(12, buttons.length) && !matchedIdx; j++) {
        fireEvent.click(buttons[i]);
        fireEvent.click(buttons[j]);
        const si = buttons[i].getAttribute("data-state") || "";
        const sj = buttons[j].getAttribute("data-state") || "";
        if (/matched/i.test(si) && /matched/i.test(sj)) {
          matchedIdx = [i, j];
        }
      }
    }
    expect(matchedIdx).not.toBeNull();

    const [mi, mj] = matchedIdx!;
    // Attempt to click matched cards again; state should remain matched, not flipped again
    const beforeI = buttons[mi].getAttribute("data-state");
    const beforeJ = buttons[mj].getAttribute("data-state");
    fireEvent.click(buttons[mi]);
    fireEvent.click(buttons[mj]);
    expect(buttons[mi].getAttribute("data-state")).toEqual(beforeI);
    expect(buttons[mj].getAttribute("data-state")).toEqual(beforeJ);
  });

  it("prevents flipping a third card while two are face-up (lock animation state)", () => {
    const r = (typeof renderWith === "function" ? renderWith : render);
    r(<MemoryMatchGame />);

    const btns = screen.getAllByRole("button");
    if (btns.length < 3) {
      expect(true).toBe(true);
      return;
    }
    fireEvent.click(btns[0]);
    fireEvent.click(btns[1]);

    const thirdBefore = btns[2].getAttribute("aria-pressed") || "false";
    fireEvent.click(btns[2]);
    const thirdAfter = btns[2].getAttribute("aria-pressed") || "false";
    // Expect that third card did not flip while resolving pair
    expect(thirdAfter).toBe(thirdBefore);
  });
});