'use client';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';

interface QuizOnboardingProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export default function QuizOnboarding({ open, onOpenChange }: QuizOnboardingProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-xl">
        <DialogHeader>
          <DialogTitle>Quiz Type Guide</DialogTitle>
          <DialogDescription>
            Here's a detailed explanation of each quiz type you can use for practice:
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 mt-4">
          <QuizTypeRow
            label="Initial"
            color="bg-blue-600"
            description="Includes all available questions in this topic, regardless of how they were created — either manually by you or automatically generated by the AI system. Use this type to begin learning a topic from scratch or to explore the full set of questions."
          />
          <QuizTypeRow
            label="Review"
            color="bg-green-600"
            description="Selects questions that are due for review based on your learning history using the SM-2 spaced repetition algorithm. This helps reinforce your memory by showing the right question at the right time, based on past performance and interval calculations."
          />
          <QuizTypeRow
            label="EF Low"
            color="bg-yellow-600"
            description="Questions with a low easiness factor (EF < 2.0). These are questions that you found difficult in the past and require more frequent review to strengthen retention."
          />
          <QuizTypeRow
            label="New"
            color="bg-purple-600"
            description="Unseen questions — ones you haven't studied yet or that haven’t been added to your review tracking system. Ideal for initial exposure to new concepts."
          />
          <QuizTypeRow
            label="Random"
            color="bg-indigo-600"
            description="Picks random questions from the entire topic, regardless of review status or difficulty. Good for refreshing general knowledge or mixing things up."
          />
          <QuizTypeRow
            label="Wrong"
            color="bg-red-600"
            description="Questions you've previously answered incorrectly in other quizzes. Use this type to target your weak areas and reinforce learning through correction."
          />
        </div>
      </DialogContent>
    </Dialog>
  );
}

function QuizTypeRow({
  label,
  description,
  color,
}: {
  label: string;
  description: string;
  color: string;
}) {
  return (
    <div className="flex items-start gap-4">
      <Button
        className={`min-w-[100px] text-white font-semibold ${color} pointer-events-none`}
      >
        {label}
      </Button>
      <p className="text-sm text-muted-foreground leading-relaxed">
        {description}
      </p>
    </div>
  );
}

