name: CI/CD pipeline release features environment

on:
  # push:
  #   tags:
  #     - 'v*.*.*'
  #     - 'release-*.*.*'
  #     - 'hotfix-*.*.*'
  #     - 'feature-*.*.*'
  #     - 'bugfix-*.*.*'
  #   paths:
  #     - 'src/**'
  #     - 'package.json'
  #   branches: [develop]
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
    branches: [develop]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        default: 'Releases'
        type: choice
        options:
          - Staging
          - Releases
          - Production

env:
  DEPLOY_DIR: /projects/release/dozu-ui
  APP_PORT: 3222
  NODE_VERSION: '18'
  PM2_APP_NAME: dozu-ui-app-release
  NODE_ENV: development
  EC2_USER: ubuntu
  EC2_HOST: '${{ secrets.EC2_HOST }}'
  SSH_KEY: '${{ secrets.EC2_SSH_KEY }}'
  SSH_OPTIONS: '-o StrictHostKeyChecking=no'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm cache clean --force
      - run: npm ci --no-audit --progress=false
      - run: npm run build
        env:
          NODE_ENV: ${{ env.NODE_ENV }}
      - name: Archive build artifacts
        run: tar -czf build.tar.gz .next package*.json
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Add Key
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
      - name: Transfer build to EC2
        run: |
          scp $SSH_OPTIONS -i private_key.pem build.tar.gz $EC2_USER@$EC2_HOST:/tmp/build.tar.gz
      - name: Deploy Application on EC2
        run: |

          ssh $SSH_OPTIONS -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          set -e
          mkdir -p "${{ env.DEPLOY_DIR }}"
          tar -xzf /tmp/build.tar.gz -C "${{ env.DEPLOY_DIR }}"
          cd "${{ env.DEPLOY_DIR }}"
          npm ci --omit=dev
          pm2 stop ${{ env.PM2_APP_NAME }} || true
          pm2 start npm --name "${{ env.PM2_APP_NAME }}" -- start -- -p ${{ env.APP_PORT }}
          pm2 save
          EOF
